name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build and Test 
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        java: [ 11 ]

    # env:

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          lfs: true

      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn -version
            
      - name: Maven repository cache
        uses: actions/cache@v1.1.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
                  ${{ runner.os }}-maven-

      - name: Update maven dependencies
        # see https://github.com/qaware/go-offline-maven-plugin
        run: mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies --no-transfer-progress
         
      - name: Build without tests
        run: mvn -ntp -DskipTests -T1C -Dfmt.action=validate install -Pexperimental

      - name: Build CRS metadata
        run: mvn -ntp -f src/metadata -Dfmt.skip clean install

      - name: Verify
        run: mvn -ntp -T1C -Dfmt.skip verify -Pexperimental -rf :geogig-api

